### ISSUE TITLE
ButtonCardJSTeplateError

### ISSUE THREAD

**Issue by xADDRx** [neilimixamo/Home-Assistant-Quick-Look-Mobile#19]
Hi guys, 

can anyone help me.

i have this error:

![grafik](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/64784940/3185d07a-7d6a-4556-858c-fbee97ae8878)

**Comment by neilimixamo** [comment]
Hi @xADDRx, these errors occur when the entity states don't match the expected values.

Header is not displaying because it seems that the state of "sensor.some_alarms_are_on" is not returning "on" or "off", but rather "undefined". Could you please check the state of this sensor in the developer tools and tell me what you see ?

The same principle applies to the two cover cards. Could you please check if your cover entities are returning "open" or "closed" states in the developer tools?

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/34e4b5b9-0cbd-486e-8f8b-8385ce8e73b1)

**Comment by neilimixamo** [comment]
Hi, did the above suggestion help you fix this issue ?

**Comment by xADDRx** [comment]
Yes Thank You!
